src/WebApplication1/Controllers/AssetsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AMS.Infrastructure;
using AMS.Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplication1.Controllers
{
    public class AssetsController : Controller
    {
        private readonly DomainDbContext context;

        public AssetsController(DomainDbContext context)
        {
            this.context = context;
        }

        public async Task<ActionResult> Index(Guid clientId, string clientName)
        {
            ViewBag.ClientId = clientId;
            ViewBag.ClientName = clientName;
            return View(await context.GetAssets(clientId));
        }

        public async Task<ActionResult> Create(Guid clientId, string clientName)
        {
            var assetTypes = await context.AssetTypes.Select(x => new { Id = x.Id, Name = x.Name }).ToListAsync();
            ViewBag.AssetTypes = new SelectList(assetTypes, "Id", "Name");
            ViewBag.ClientId = clientId;
            ViewBag.ClientName = clientName;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(DefaultAsset asset)
        {
            try
            {
                await context.AddAsset(asset);

                return RedirectToAction(nameof(Index), new { clientId = asset.Client.Id });
            }
            catch(Exception ex)
            {
                ;
                return View();
            }
        }

        public async Task<ActionResult> Edit(Guid id, Guid clientId)
        {
            var assetTypes = await context.AssetTypes.Select(x => new { Id = x.Id, Name = x.Name }).ToListAsync();
            ViewBag.AssetTypes = new SelectList(assetTypes, "Id", "Name");
            DefaultAsset model = await context.GetAssetById(id, clientId);
            ViewBag.ClientId = clientId;
            ViewBag.ClientName = model.Client.Name;

            return base.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid id, DefaultAsset asset)
        {
            try
            {
                await context.UpdateAsset(asset);

                return RedirectToAction(nameof(Index), new { clientId = asset.Client.Id });
            }
            catch
            {
                return View();
            }
        }

    }
}

src/WebApplication1/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AMS.Infrastructure;
using AMS.Infrastructure.Models;

namespace WebApplication1.Controllers
{
    public class ClientsController : Controller
    {
        private readonly DomainDbContext context;

        public ClientsController(DomainDbContext context)
        {
            this.context = context;
        }

        // GET: Clients
        public async Task<ActionResult> Index()
        {
            return View(await context.GetClients());
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Client client)
        {
            try
            {
                await context.AddClient(client);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Clients/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            return View(await context.GetClientById(id));
        }

        // POST: Clients/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid id, Client client)
        {
            try
            {
                await context.UpdateClient(client);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        
    }
}

src/WebApplication1/Views/Clients/Create.cshtml
@model AMS.Infrastructure.Models.Client

<h3>Client</h3>

<form asp-action="Create" method="post">
    <div class="row">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" />
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
        <a asp-action="Index" class="btn">Cancel</a>
    </div>
</form>

src/WebApplication1/Views/Clients/Edit.cshtml
@model AMS.Infrastructure.Models.Client

<h3>Client</h3>

<form asp-action="Edit" method="post">
    <div class="row">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" />
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
        <a asp-action="Index" class="btn">Cancel</a>
    </div>
</form>

src/WebApplication1/Views/Clients/Index.cshtml
@model IEnumerable<AMS.Infrastructure.Models.Client>

<h3>Clients</h3>

<p class="mt-2">
    <a class="btn btn-primary" asp-action="Create">Create</a>
</p>
<div class="row mt-2">
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var client in Model)
            {
                <tr>
                    <td>@client.Id</td>
                    <td>@client.Name</td>
                    <td>
                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@client.Id">Edit</a>
                        <a class="btn btn-success" asp-controller="Assets" asp-action="Index" asp-route-clientId="@client.Id" asp-route-clientName="@client.Name">Assets</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>