src/WebApplication1/Areas/Api/Controllers/FoldersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AMS.Infrastructure;
using Shared.DocumentModels;

namespace WebApplication1.Areas.Api.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class FoldersController : ControllerBase
    {
        private readonly DomainDbContext _context;

        public FoldersController(DomainDbContext context)
        {
            _context = context;
        }

        // GET: api/Folders
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Folder>>> GetFolders(Guid repositoryId, Guid? parentId = null)
        {
            return await _context.Folders.Where(x => x.RepositoryId == repositoryId 
                && ((!parentId.HasValue && !x.ParentId.HasValue) || (parentId.HasValue && x.ParentId == parentId))
                ).ToListAsync();
        }

        // GET: api/Folders/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Folder>> GetFolder(Guid id)
        {
            var folder = await _context.Folders
                .Include(p => p.Documents)
                .Include(p => p.Parent)
                .Include(p => p.Childs)
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();

            if (folder == null)
            {
                return NotFound();
            }

            return folder;
        }

        // PUT: api/Folders/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutFolder(Guid id, Folder folder)
        {
            if (id != folder.Id)
            {
                return BadRequest();
            }

            _context.Entry(folder).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FolderExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Folders
        [HttpPost]
        public async Task<ActionResult<Folder>> PostFolder(Folder folder)
        {
            _context.Folders.Add(folder);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetFolder", new { id = folder.Id }, folder);
        }

        // DELETE: api/Folders/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Folder>> DeleteFolder(Guid id)
        {
            var folder = await _context.Folders.FindAsync(id);
            if (folder == null)
            {
                return NotFound();
            }

            _context.Folders.Remove(folder);
            await _context.SaveChangesAsync();

            return folder;
        }

        private bool FolderExists(Guid id)
        {
            return _context.Folders.Any(e => e.Id == id);
        }
    }
}

src/WebApplication1/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AMS.Infrastructure;
using Shared.DocumentModels;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace WebApplication1.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly DomainDbContext _context;

        public DocumentsController(DomainDbContext context)
        {
            _context = context;
        }

        // GET: Documents
        public async Task<IActionResult> Index(Guid repositoryId, Guid? folderId = null)
        {
            var domainDbContext = _context.Documents.Include(d => d.Folder).Include(d => d.Repository)
                .Where(x => x.RepositoryId == repositoryId 
                    && (!folderId.HasValue || x.FolderId == folderId)
                );
            return View(await domainDbContext.ToListAsync());
        }

        // GET: Documents/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(d => d.Folder)
                .Include(d => d.Repository)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // GET: Documents/Create
        public IActionResult Create()
        {
            ViewData["FolderId"] = new SelectList(_context.Folders, "Id", "Title");
            ViewData["RepositoryId"] = new SelectList(_context.Repositories, "Id", "Name");

            return View();
        }

        // POST: Documents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RepositoryId,FolderId,Title,CreationTime,LastModificationTime,Comments")] Document document, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                document.Id = Guid.NewGuid();
               
                var docFile = new DocumentFile()
                {
                    Id = Guid.NewGuid(),
                    Document = document,
                    FileName = file.FileName,
                    FileSize = file.Length,
                    FileCreationTime = DateTime.Now,
                    FileLastModificationTime = DateTime.Now
                };
                var chunk = new FileChunk()
                {
                    Id = Guid.NewGuid(),
                    DocumentFile = docFile,
                    SNO = 1
                };
                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    chunk.Contents = memoryStream.ToArray();
                }
                docFile.Chunks.Add(chunk);
                document.Files.Add(docFile);

                _context.Add(document);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FolderId"] = new SelectList(_context.Folders, "Id", "Title", document.FolderId);
            ViewData["RepositoryId"] = new SelectList(_context.Repositories, "Id", "Name", document.RepositoryId);
            return View(document);
        }

        // GET: Documents/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents.FindAsync(id);
            if (document == null)
            {
                return NotFound();
            }
            ViewData["FolderId"] = new SelectList(_context.Folders, "Id", "Title", document.FolderId);
            ViewData["RepositoryId"] = new SelectList(_context.Repositories, "Id", "Name", document.RepositoryId);
            return View(document);
        }

        // POST: Documents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,RepositoryId,FolderId,Title,CreationTime,LastModificationTime,Comments")] Document document)
        {
            if (id != document.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(document);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DocumentExists(document.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FolderId"] = new SelectList(_context.Folders, "Id", "Title", document.FolderId);
            ViewData["RepositoryId"] = new SelectList(_context.Repositories, "Id", "Name", document.RepositoryId);
            return View(document);
        }

        // GET: Documents/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(d => d.Folder)
                .Include(d => d.Repository)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // POST: Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var document = await _context.Documents.FindAsync(id);
            _context.Documents.Remove(document);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DocumentExists(Guid id)
        {
            return _context.Documents.Any(e => e.Id == id);
        }

        public IActionResult Download(Guid id)
        {
            var docFile = _context.DocumentFiles.Include(x => x.Chunks).Where(x => x.DocumentId == id).FirstOrDefault();
            var chunk = docFile.Chunks.FirstOrDefault();
            var mem = new MemoryStream(chunk.Contents);
            return File(mem, "application/octet-stream", docFile.FileName);
        }
    }
}

src/WebApplication1/Controllers/FoldersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AMS.Infrastructure;
using Shared.DocumentModels;

namespace WebApplication1.Controllers
{
    public class FoldersController : Controller
    {
        private readonly DomainDbContext _context;

        public FoldersController(DomainDbContext context)
        {
            _context = context;
        }

        // GET: Folders
        public async Task<IActionResult> Index(Guid repositoryId, Guid? parentId = null)
        {
            var domainDbContext = _context.Folders.Include(f => f.Parent).Include(f => f.Repository)
                .Where(x => x.RepositoryId == repositoryId
                    && ((!parentId.HasValue && !x.ParentId.HasValue) || (parentId.HasValue && x.ParentId == parentId))
                );
            return View(await domainDbContext.ToListAsync());
        }

        // GET: Folders/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .Include(f => f.Parent)
                .Include(f => f.Repository)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (folder == null)
            {
                return NotFound();
            }

            return View(folder);
        }

        // GET: Folders/Create
        public IActionResult Create()
        {
            ViewData["ParentId"] = new SelectList(_context.Folders, "Id", "Title");
            ViewData["RepositoryId"] = new SelectList(_context.Repositories, "Id", "Name");
            return View();
        }

        // POST: Folders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RepositoryId,ParentId,Title,Comments")] Folder folder)
        {
            if (ModelState.IsValid)
            {
                folder.Id = Guid.NewGuid();
                _context.Add(folder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentId"] = new SelectList(_context.Folders, "Id", "Title", folder.ParentId);
            ViewData["RepositoryId"] = new SelectList(_context.Repositories, "Id", "Name", folder.RepositoryId);
            return View(folder);
        }

        // GET: Folders/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders.FindAsync(id);
            if (folder == null)
            {
                return NotFound();
            }
            ViewData["ParentId"] = new SelectList(_context.Folders, "Id", "Title", folder.ParentId);
            ViewData["RepositoryId"] = new SelectList(_context.Repositories, "Id", "Name", folder.RepositoryId);
            return View(folder);
        }

        // POST: Folders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,RepositoryId,ParentId,Title,Comments")] Folder folder)
        {
            if (id != folder.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(folder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FolderExists(folder.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentId"] = new SelectList(_context.Folders, "Id", "Title", folder.ParentId);
            ViewData["RepositoryId"] = new SelectList(_context.Repositories, "Id", "Name", folder.RepositoryId);
            return View(folder);
        }

        // GET: Folders/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .Include(f => f.Parent)
                .Include(f => f.Repository)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (folder == null)
            {
                return NotFound();
            }

            return View(folder);
        }

        // POST: Folders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var folder = await _context.Folders.FindAsync(id);
            _context.Folders.Remove(folder);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FolderExists(Guid id)
        {
            return _context.Folders.Any(e => e.Id == id);
        }
    }
}

src/WebApplication1/Views/Folders/Create.cshtml
@model Shared.DocumentModels.Folder

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Folder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RepositoryId" class="control-label"></label>
                <select asp-for="RepositoryId" class ="form-control" asp-items="ViewBag.RepositoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ParentId" class="control-label"></label>
                <select asp-for="ParentId" class ="form-control" asp-items="ViewBag.ParentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/WebApplication1/Views/Folders/Delete.cshtml
@model Shared.DocumentModels.Folder

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Folder</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Repository)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Repository.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Parent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Parent.Title)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/WebApplication1/Views/Folders/Details.cshtml
@model Shared.DocumentModels.Folder

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Folder</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Repository)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Repository.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Parent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Parent.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/WebApplication1/Views/Folders/Edit.cshtml
@model Shared.DocumentModels.Folder

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Folder</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RepositoryId" class="control-label"></label>
                <select asp-for="RepositoryId" class="form-control" asp-items="ViewBag.RepositoryId"></select>
                <span asp-validation-for="RepositoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParentId" class="control-label"></label>
                <select asp-for="ParentId" class="form-control" asp-items="ViewBag.ParentId"></select>
                <span asp-validation-for="ParentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/WebApplication1/Views/Folders/Index.cshtml
@model IEnumerable<Shared.DocumentModels.Folder>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Repository)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comments)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Repository.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parent.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comments)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                <a asp-action="Index" asp-route-repositoryId="@item.RepositoryId" asp-route-parentId="@item.Id">Contents</a>
                <a asp-controller="Documents" asp-action="Index" asp-route-repositoryId="@item.RepositoryId" asp-route-folderId="@item.Id">Contents</a>
            </td>
        </tr>
}
    </tbody>
</table>